
services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:password@db:5432/lin_flask  # DB connection (use env vars)
    networks:
      - app-network

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: lin_flask
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d lin_flask"]
      interval: 5s
      timeout: 5s
      retries: 5  

networks:
  app-network:

volumes:
  db-data:
