version: '3.8'
services:
  app:
    build: .  # Build from Dockerfile
    ports:
      - "5000:5000"  # Map port
    depends_on:
      - db  # Wait for DB
    environment:
      - DATABASE_URI=postgresql://postgres:password@db:5432/lin_flask  # DB connection (use env vars)
    networks:
      - app-network

  db:
    image: postgres:16  # Postgres image
    environment:
      POSTGRES_DB: lin_flask
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data  # Persistent volume
    networks:
      - app-network

networks:
  app-network:  # Internal network

volumes:
  db-data:  # Volume name