# Ansible Inventory File for CRUD Flask Application

[ec2_instances]
flask-app-server ansible_host=13.232.14.249 ansible_user=ec2-user ansible_ssh_private_key_file=C:\path\to\your\key.pem

[kubernetes_local]
minikube ansible_connection=local

[docker_hosts]
localhost ansible_connection=local

[dev:children]
docker_hosts
kubernetes_local

[prod:children]
ec2_instances

[all:vars]
ansible_python_interpreter=/usr/bin/python3
